version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - type: volume
        source: shopper_development
        target: /var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  test:
    build: .
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    command: sh -c "rake db:create db:schema:load db:seed && cucumber --format html --out report.html --format pretty"
=======
    command: sh -c "bundle exec rake db:test:clone_structure && cucumber --format html --out report.html --format pretty"
>>>>>>> 6968fe1... change cucumber enviroment to test db
=======
    command: sh -c "bundle exec rake db:drop RAILS_ENV=test &&
=======
    command: sh -c "bundle exec rake db:drop &&
>>>>>>> e62127c... edite docker-compose for ci
                    bundle exec rake db:create &&
                    bundle exec rake db:schema:load &&
                    bundle exec rake db:seed &&
=======
    command: sh -c "bundle exec rake db:reset RAILS_ENV=test &&
                    bundle exec rake db:schema:load RAILS_ENV=test &&
                    bundle exec rake db:seed RAILS_ENV=test &&
>>>>>>> 0c31ff1... db reset instead of drop and create
                    cucumber --format html --out report.html --format pretty"
>>>>>>> d050bee... setting test enviroment for cucumber tests

    volumes:
      - .:/myapp


volumes:
  shopper_development:
    name: shopper_development