version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    user: "${UID}:${GID}"
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  test:
    build: .
<<<<<<< HEAD
    command: cucumber --format html --out test-reports/report.html --format pretty
=======
#    command: cucumber --format html --out report.html --format pretty
    command: sh -c "cucumber --format html --out report.html --format pretty && pwd && ls"

>>>>>>> bf138d8... test
    volumes:
<<<<<<< HEAD
      - .:/myapp
=======
      - .:/myapp

volumes:
  shopper_development:
    name: shopper_development
>>>>>>> 993b4b4... test
