version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - type: volume
        source: shopper_development
        target: /var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  test:
    build: .
    command: sh -c "bundle exec rake db:reset RAILS_ENV=test &&
      cucumber --format html --out test_reports/report.html --format pretty"

    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  shopper_development:
    name: shopper_development