#!/bin/bash
sudo docker system prune -f
sudo docker stop $(sudo docker ps -a -q)
sudo docker rm $(sudo docker ps -a -q)
sudo docker-compose build web db
sudo docker-compose up -d --force-recreate web db
sudo docker-compose run -d web