#!/bin/bash
sudo docker system prune -f
sudo docker stop $(docker ps -a -q)
sudo docker rm $(docker ps -a -q)
sudo docker-compose build web db
sudo docker-compose up -d --force-recreate
sudo docker-compose run -d web